const images = {
  applications_with_bill: require("./applications-with-bill.png"),
  bell: require("./bell.png"),
  gscwd_logo: require("./gscwd-logo.png"),
  leakage_logo: require("./leakage-logo.png"),
  module_bg_image: require("./module-bg-image.png"),
  modules_bg_image: require("./modules-bg-image.png"),
  new_service_applications: require("./new-service-applications.png"),
  approved_new_service_applications: require("./approved-new-service-applications.png"),
  disapproved_new_service_applications: require("./disapproved-new-service-applications.png"),
  pending_new_service_applications: require("./pending-new-service-applications.png"),
  nsa_logo: require("./nsa-logo.png"),
  omms_logo: require("./omms-logo.png"),
  others: require("./others.png"),
  sample_avatar: require("./sample-avatar.png"),
  sample_avatar_2: require("./sample-avatar-2.png"),
  sample_map: require("./sample-map.png"),
  sidebar_bg: require("./sidebar-bg.png"),
  suspended_areas: require("./suspended-areas.png"),
  total_installation: require("./total-installation.png"),
  total_service_connections: require("./total-service-connections.png"),
  water_meter_logo: require("./water-meter-logo.png"),
  water_test_logo: require("./water-test-logo.png"),
};

export default images;
