import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { ThemeProvider, QueryClientProvider } from "@mapstudio/lib/providers";
import { SonnerToast, Toaster } from "@mapstudio/lib/components/ui";
import "@mapstudio/styles/tailwind.css";
import "@mapstudio/styles/ol.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-screen w-screen overflow-x-hidden overflow-y-hidden`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProvider>{children}</QueryClientProvider>
        </ThemeProvider>
        <Toaster />
        <SonnerToast />
      </body>
    </html>
  );
}
