import "@mapstudio/styles/tailwind.css";
import "@mapstudio/styles/ol.css";

import type { Metadata } from "next";
import type { PropsWithChildren } from "react";
import { Inter } from "next/font/google";
import { SonnerToast, Toaster } from "@mapstudio/lib/components/ui";
import { GrowthBookClientProvider } from "@mapstudio/lib/providers/GrowthBookClientProvider";
import { QueryClientProvider } from "@mapstudio/lib/providers/QueryClientProvider";
import { ThemeProvider } from "@mapstudio/lib/providers/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mapstudio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} h-screen w-screen overflow-x-hidden overflow-y-hidden`}>
        <GrowthBookClientProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <QueryClientProvider>{children}</QueryClientProvider>
          </ThemeProvider>
          <Toaster />
          <SonnerToast />
        </GrowthBookClientProvider>
      </body>
    </html>
  );
}
